spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
  h2:
    console:
      path: /h2


project-description: '@project.description@'
project-title: Spring Data Projection
project-version: '@project.version@'